name = "tui"
description = "hax0r"
homepage = "https://localhost"
license = "MIT"
licenselink = "https://localhost"
# tags = ["blog", "retro", "dos", "terminal"]
# features = [
#   "minimalistic blog",
# ]
# min_version = 0.55
# 
# [author]
#   name = "GoatFoo"
#   homepage = "https://goatpr0n.farm"
# 
