name = "hax0r"
description = "hax0r lulz"
homepage = "https://localhost"
license = "MIT"
licenselink = "https://localhost"
tags = ["blog", "minimalistic", "dark", "ascii"]
features = [
  "minimalistic blog",
]
min_version = 0.55

[author]
  name = "GoatFoo"
  homepage = "https://goatpr0n.farm"
